### ISSUE TITLE
Min-max-scaler in Preprocessing Can't Be Trained on Vectors

### ISSUE THREAD

**Issue by rnowling** [rinuboney/clatern#25]
Min-max-scaler can only be trained on matrices, not vectors.

**Comment by rinuboney** [comment]
What is the need for training a min-max scaler on a vector?

**Comment by rnowling** [comment]
I don't have a concrete use case at the moment.  We could close this issue as "not supported" until someone actually needs the capability.

**Comment by rinuboney** [comment]
If somebody actually needs it then they can just wrap the vector into a matrix.

**Comment by rnowling** [comment]
Sounds good to me.  Closing the issue.
